package com.Market.MeatShop.Utils;

public enum SystemAuthorities {
  PRODUCT_MANAGEMENT,
  CATEGORY_MANAGEMENT,
  STOCK_MANAGEMENT,
  EMPLOYEE_MANAGEMENT,
  SELL_BUY_AUTHORITY,
  PARTY_MANAGEMENT,
  VIEW_PRODUCTS,
  VIEW_CATEGORIES
}
