CREATE SEQUENCE IF NOT EXISTS parties_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS party_contacts_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS categories_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS products_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS product_components_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS employees_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS invoices_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS invoice_components_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS cash_transactions_seq
    START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS stock_movments_seq
    START WITH 1 INCREMENT BY 50;