name: Build and Deploy MeatShopApp



on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-deploy:
    name: Build and Deploy MeatShopApp
    runs-on: self-hosted

    environment: dev
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: make environment file
        run: |
          
          echo 'DB_NAME=${{ secrets.DB_NAME }}' > Docker/.env
          chown -R $USER:$USER Docker/.env
          chmod 600 Docker/.env
          echo 'DB_USER=${{ secrets.DB_USER }}' >> Docker/.env
          echo 'DB_PASS=${{ secrets.DB_PASS }}' >> Docker/.env
          echo 'DB_PORT=${{ secrets.DB_PORT }}' >> Docker/.env
          echo 'REDIS_HOST=${{ secrets.REDIS_HOST }}' >> Docker/.env
          echo 'REDIS_PORT=${{ secrets.REDIS_PORT }}' >> Docker/.env
          echo 'REDIS_TIME_OUT=${{ secrets.REDIS_TIME_OUT }}' >> Docker/.env
          echo 'MAX_REDIS_ACTIVE=${{ secrets.MAX_REDIS_ACTIVE }}' >> Docker/.env
          echo 'MAX_REDIS_IDLE=${{ secrets.MAX_REDIS_IDLE }}' >> Docker/.env
          echo 'MIN_REDIS_IDLE=${{ secrets.MIN_REDIS_IDLE }}' >> Docker/.env
          echo 'MAX_REDIS_WAIT=${{ secrets.MAX_REDIS_WAIT }}' >> Docker/.env
          echo 'SPRING_WEB_LOG_LEVEL=${{ secrets.SPRING_WEB_LOG_LEVEL}}' >> Docker/.env
          echo 'SPRING_SECURITY_LOG_LEVEL=${{ secrets.SPRING_SECURITY_LOG_LEVEL }}' >> Docker/.env
          echo 'SPRING_HIBERNATE_LOG_LEVEL=${{ secrets.SPRING_HIBERNATE_LOG_LEVEL }}' >> Docker/.env
          echo 'SPRING_MEAT_SHOP_LOG_LEVEL=${{ secrets.SPRING_MEAT_SHOP_LOG_LEVEL }}' >> Docker/.env
          echo 'GF_SECURITY_ADMIN_USER=${{ secrets.GF_SECURITY_ADMIN_USER}}' >> Docker/.env
          echo 'GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}' >> Docker/.env
          echo 'GF_USERS_ALLOW_SIGN_UP=${{ secrets.GF_USERS_ALLOW_SIGN_UP }}' >> Docker/.env
          echo 'GF_SERVER_HTTP_PORT=${{ secrets.GF_SERVER_HTTP_PORT }}' >> Docker/.env
          echo 'LOKI_SERVER_HTTP_PORT=${{ secrets.LOKI_SERVER_HTTP_PORT }}' >> Docker/.env
          echo 'BACKEND_VERSION=$(cat VERSION)' >> Docker/.env
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Java and Maven
        run: |
          java -version
          mvn -version


      #      - name: Build Maven Project
      #        working-directory: BackEnd
      #        run: mvn clean install -DskipTests
      #
      #      - name: Build Backend Docker Image
      #        working-directory: BackEnd
      #        run: docker build -t aehamalhaeak/meat_shop:latest .



      - name: Run Docker Compose
        run: |
          cd Docker
          docker compose down || true
          docker compose up -d

      - name: Check Containers
        run: docker ps