name: Build and deploy MeatShopApp
runs-on: self-hosted
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy MeatShopApp
    steps:
      - name: docker compose build
        run: docker compose up
